### ISSUE TITLE
Passing in values file with -f flag

### ISSUE THREAD

**Issue by mahgo** [datreeio/helm-datree#16]
**Describe the solution you'd like**
Is it currently possible to pass in values files with a -f flag? This is something I'd like to be able to do.

**Comment by eyarz** [comment]
If you need to pass helm arguments to your template, you will need to add `--` before them:
```
helm datree test [CHART_DIRECTORY] -- --values values.yaml
```

**Comment by mahgo** [comment]
Thanks!
