### ISSUE TITLE
Chart name contains spaces

### ISSUE THREAD

**Issue by termit-uanic** [datreeio/helm-datree#17]
If there are spaces in the title of the diagram, there will be an error

Chart.yaml
```
apiVersion: v2
name: Test Chart v2
description: A Helm chart for Kubernetes
```

```
❯ helm datree test ./ -- --values values.yaml --values values-test.yaml --set namespace=test
~/.local/share/helm/plugins/helm-datree/scripts/run.sh: line 34: $tempManifestPath: ambiguous redirect
Error: plugin "datree" exited with error
```

You should quote the variable `$tempManifestPath`

run.sh
```
helm template "${helm_options[@]}" "$helm_chart_location" > "$tempManifestPath"
$HELM_PLUGIN_DIR/bin/datree "${datree_options[@]}" "$tempManifestPath"
```

**Comment by termit-uanic** [comment]
sorry
Hastened to send a bug

**Comment by romanlab** [comment]
For future reference if anyone finds it - the reason this is not a bug is because the helm chart name is used as a DNS record and dns disallows spaces(and uppercase letters and underscores). From [helm](https://helm.sh/docs/chart_best_practices/conventions/) docs
