### ISSUE TITLE
Allow use with other installations of helm

### ISSUE THREAD

**Issue by geisterfurz007** [datreeio/helm-datree#23]
**Is your feature request related to a problem? Please describe.**

I am using the helm3 plugin/addon of microk8s which is run using `microk8s helm3`; for easier personal use I just aliased that to `helm` but `run.sh` doesn't pick that up causing the datree plugin to not compile the chart which in turn causes a "No files detected" error since this line (specifically `helm show chart`) fails as the command isn't known:

https://github.com/datreeio/helm-datree/blob/c4146ef33895739b5634a1e8a8e524159a5d3f3e/scripts/run.sh#L16

**Describe the solution you'd like**

Some flag / env variable for the script to provide an alternative path / way of calling helm to allow executing helm that is prebundled with other tools and thus requires a different command to run.

**Describe alternatives you've considered**

- Modifying the installed `run.sh` file to include the alias at the top of the file locally
- Dropping a `helm` executable somewhere in the path that essentially serves as the alias

**Additional context**
\-

**Comment by dimabru** [comment]
Hi @geisterfurz007,
Thanks a lot for reporting this!
I'm marking this issue as up for grabs

**Comment by dimabru** [comment]
@geisterfurz007
BTW, if you were able to find the issue location and suggest a solution I think you are deffinitely skilled enough to fix this yourself :)
If you'd like to take this on, please let me know. We can schedule a zoom call and talk about a possible solution

**Comment by geisterfurz007** [comment]
I think I might actually have something in mind; I will try around with it later and open a PR if it works; otherwise I Will gladly come back to the zoom call offer, thanks a lot!

**Comment by dimabru** [comment]
Great :)
