### ISSUE TITLE
Installation of Helm plugin failed

### ISSUE THREAD

**Issue by AreebAbdulGhani** [datreeio/helm-datree#29]
While installing plugin on windows 11
It says
Error: exec: "sh": executable file not found in %PATH%

![Screenshot 2022-03-26 104835](https://user-images.githubusercontent.com/92576221/160225917-46105453-5e86-4fb0-8470-2c125d289fcc.png)

**Comment by eyarz** [comment]
@AreebAbdulGhani unfortunately, helm doesn't support installing plugins on windows (yet):
https://github.com/helm/helm/issues/7117

We will update the readme to conation this info.

**Comment by AreebAbdulGhani** [comment]
No worries, Thanks for letting me know.
