### ISSUE TITLE
Installation sometimes fails in Travis CI

### ISSUE THREAD

**Issue by royhadad** [datreeio/helm-datree#32]
**Describe the bug**
I'm running datree in Travis CI using the helm plugin, installing it on every CI run.
`helm plugin install https://github.com/datreeio/helm-datree` 
The installation fails about 1 out of 3 times, which stops my CI and fails my build. 

**To Reproduce**
1. Run `helm plugin install https://github.com/datreeio/helm-datree` in Travis CI (might work locally as well)
2. The CI sometimes fails to install

**Expected behavior**
Installation should work and CI continue

**Screenshots**
![Screen Shot 2022-03-31 at 13 25 44](https://user-images.githubusercontent.com/39004075/161034490-8677fdb0-6410-4152-8f59-ef8860dc3263.png)

**Desktop (please complete the following information):**
 - OS: Travis CI, Ubuntu Trusty (in travis.yaml `dist: trusty`)

**Datree plugin version (run `helm datree verion`):**
 - Version: 1.1.10 (happens in other versions)

**Additional context**  
This may have nothing to do with Travis CI, but rather with the github servers.

**Comment by hadar-co** [comment]
@royhadad @MentalBrake 
You can use the new docker image in your CI and avoid needing to download/install helm:
https://hub.docker.com/r/datree/datreeci
