### ISSUE TITLE
Add pre-commit-hooks feature for helm-datree

### ISSUE THREAD

**Issue by angelwcrypto** [datreeio/helm-datree#33]
**Is your feature request related to a problem? Please describe.**
I would not want to commit to the repos every time I work with fixing the policies. So pre-commit-hooks are useful to Helm Charts users

**Describe the solution you'd like**
It would be nice to have pre-commit hooks feature as well for the Helm Chart users.

Something like this: 
- id: install-datree
  name: datree helm install
  description: Run Helm charts against the datree policy
  require_serial: true
  pass_filenames: true
  entry: scripts/install.sh
  language: script
  files: [file, yaml]

- id: run-datree
  name: datree helm test
  description: Run Helm charts against the datree policy
  require_serial: true
  pass_filenames: true
  entry: scripts/run.sh
  language: script
  files: [file, yaml]

Thank you!

**Comment by eyarz** [comment]
@angelwcrypto why did you decide to close this issue?

**Comment by angelwcrypto** [comment]
@eyarz I thought I have some typos

**Comment by angelwcrypto** [comment]
Sorry about that, could you help with taking a look into a possible enhancement for the helm datree? I must say that I like the simplicity of the tool a lot.

**Comment by eyarz** [comment]
Sure, but why don't you open a PR with a configured `.pre-commit-hooks.yaml` file?
I'm not a pre-commit expert, but I'm a little familiar with that for [Datree's CLI project](https://github.com/datreeio/datree/blob/main/.pre-commit-hooks.yaml).
