### ISSUE TITLE
Recursive test for helm validation

### ISSUE THREAD

**Issue by vaibhav-fx** [datreeio/helm-datree#40]
**Is your feature request related to a problem? Please describe.**
I want to run datree against a  bunch of helm charts checked into a single repo. Everytime I add a new repo, I have to manually add in github actions / config to run it against a specific chart. 

**Describe the solution you'd like**
I want to be able to recursively specify a master folder with helm charts against which I want to run datree. I am also fine to follow a certain convention of naming the custom values files or maintain a config file for this

**Describe alternatives you've considered**
Considering a script which user has to run which generates this and adds to the github actions. But don't want to add that capability to user

**Additional context**

**Comment by hadar-co** [comment]
Hi @vaibhav-fx!
Our github action only supports helm native commands, which means if that you can't do it with helm, you will not be able to do it with the github action.
As a general workaround, you can create a bash script that will iterate over your directories and run `helm datree test` against each of them, something like this:

```
for chartDir in $(find /parentDir/ -mindepth 1 -maxdepth 1 -type d) ; do
    helm datree test $chartDir
done
```

**Comment by eyarz** [comment]
also added to the readme of this project:
https://github.com/datreeio/helm-datree#testing-multiple-charts
