### ISSUE TITLE
Choose values file

### ISSUE THREAD

**Issue by typro33333** [datreeio/helm-datree#50]
I think need args "-f" to choose file values. Because my file values.yml not in the same folder chart.

**Comment by eyarz** [comment]
`-f` and `--values` are [the same](https://helm.sh/docs/helm/helm_install/#options).

you can pass them as listed in the [readme](https://github.com/datreeio/helm-datree#passing-arguments):
`helm datree test [CHART_DIRECTORY] -- -f values.yaml`

**Comment by typro33333** [comment]
@eyarz  Thanks so much.
