### ISSUE TITLE
helm datree test my-app/ doesn't work on Windows WSL

### ISSUE THREAD

**Issue by proxyvert** [datreeio/helm-datree#51]
**Describe the bug**
command 'helm datree test my-test-app/'
gives the following error:
  Error: unknown flag: --skip-tests
  Error: plugin "datree" exited with error

**To Reproduce**
1. Run command 'helm create my-test-app'
2. Run command 'helm datree test my-test-app/'
3. See error:  
      Error: unknown flag: --skip-tests
      Error: plugin "datree" exited with error

**Expected behavior**
Output similar to datree test my-test-app.yaml (helm template my-test-app/ > my-test-app.yaml; datree test my-test-app.yaml)

**Screenshots**
![image](https://user-images.githubusercontent.com/57131317/220545793-21c52f17-b57c-4edc-9e28-880a7a651fc9.png)

**Desktop (please complete the following information):**
 - OS: Windows WSL2 Ubuntu

**Datree plugin version (run `helm datree verion`):**
 - Version: 1.8.27

**Additional context**

**Comment by eyarz** [comment]
@PaleIntrovert can you please try to pass a dir name without the dashes (`-`) and let us know if this is working? (e.g `myTestApp/`) 
I suspect it is a bug related to the plunging parsing the CLI params.

**Comment by proxyvert** [comment]
@eyarz it definetely helped, but there is another bug it didn't work with 'test_app/' but worked with 'test_app/*'
![image](https://user-images.githubusercontent.com/57131317/220882966-c3d4ac86-1945-4bfe-9da8-3581de12c344.png)

**Comment by hadar-co** [comment]
Hi @PaleIntrovert , I'm trying to reproduce this but no success so far, even when using a chart name like `my-test-app` with dashes.
I'm running helm version 3.11.1 (I see you're running v3.2.0). I found some references saying that the `--skip-tests` flag that we use is supported in Helm version 3.5 and higher. 
Can you try to update helm and run again?

**Comment by proxyvert** [comment]
Hi @hadar-co, I installed helm version 3.11.1, looks like the problem is gone. I have one question, It says there is no internet connection, so it cannot check schema validation. How can I make it work, I have envs http_proxy, https_proxy, no_proxy configured.
![image](https://user-images.githubusercontent.com/57131317/221747648-ebbd25c6-7075-4af9-a02f-36f8e56f845d.png)

**Comment by hadar-co** [comment]
@PaleIntrovert Glad to see that it fixed your issue 👍
Regarding the internet connection - since I do not know your environment, I can't say for sure what the issue is.
The schema validation step fetches the schemas from Github, so let's try that - try to curl a schema directly from your env and see if it works:
`curl https://github.com/yannh/kubernetes-json-schema/blob/master/v1.22.7-standalone/deployment-apps-v1.json`

**Comment by proxyvert** [comment]
@hadar-co I tried curl command, and it works, so it means my proxy envs are working, why helm datree plugin doesn't respect them? Should I add something to helm config?

**Comment by hadar-co** [comment]
Datree uses [Kubeconform](https://github.com/yannh/kubeconform) to perform schema validation. In [their docs](https://github.com/yannh/kubeconform#proxy-support) they show how to use an https proxy.
To understand if this is an issue on our side or theirs, please run kubeconform using the proxy as shown in the link and let us know if it works. If it does, then we have a bug and we will fix it.
We will keep this open until we get your result. Thanks

**Comment by proxyvert** [comment]
@hadar-co it seems our corporate proxy hijacks certs, and it is my issue, not kubeconfig's or datree's.
![image](https://user-images.githubusercontent.com/57131317/222367020-3a51003d-4ac1-4661-9424-f8d29a878af1.png)
I will install proxy's certificate inside WSL, and will update on my results with proposed command.

**Comment by hadar-co** [comment]
@PaleIntrovert Thanks for the update:)

**Comment by proxyvert** [comment]
@hadar-co here are results:
![image](https://user-images.githubusercontent.com/57131317/222373189-ae596da9-b311-40f3-84fd-0124c63393b0.png)
